# Generated by Django 5.0 on 2024-06-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_revenue_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='incoming',
            name='incoming_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
