# Generated by Django 5.0 on 2024-06-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0004_incoming_incoming_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incoming",
            name="incoming_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
