# Generated by Django 5.0 on 2024-06-27 23:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_incoming_incoming_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('user_email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=255)),
                ('alert_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revenue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.revenue')),
            ],
        ),
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('limit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('limit_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='budget.revenuecategory')),
            ],
        ),
    ]
