# Generated by Django 5.0 on 2024-06-27 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0005_alert_limit"),
        ("budget", "0005_alter_incoming_incoming_date"),
    ]

    operations = []
