# Generated by Django 5.0 on 2024-07-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0005_alert_limit"),
        ("budget", "0005_alter_incoming_incoming_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incoming",
            name="launch_date",
            field=models.DateTimeField(blank=True),
        ),
    ]
