# Generated by Django 5.0 on 2024-07-10 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_alter_incoming_incoming_date'),
        ('budget', '0006_alter_incoming_launch_date'),
    ]

    operations = [
    ]
