# Generated by Django 5.0 on 2024-07-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0007_merge_20240709_2228"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incoming",
            name="incoming_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="incoming",
            name="launch_date",
            field=models.DateField(blank=True),
        ),
    ]
