[project]
name = "GammaBudget"
version = "0.1.0"

[build-system]
requires = ["Django==5.0", "setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["budget", "core", "project"]